---
- name: Configure OPS445 Linux VM machine
  hosts: vmlab
  user: student
  become: yes
  tasks:
    - name: Update Apache
      action: yum name=httpd state=latest

    - name: Install EPEL repository
      action: yum name=epel-release state=present

    - name: Remove tree
      action: yum name=tree state=absent

    - name: Set the hostname
      action: hostname name=mpopov

    - name: Create new user
      user:
        name: "mpopov"
        shell: /bin/bash
        groups: wheel
        append: yes

    - name: Allow user to sudo without password
      copy:
        dest: "/etc/sudoers.d/mpopov"
        content: "mpopov ALL=(ALL) NOPASSWD:ALL"

    - name: Check for .ssh directory on managed machine
      file:
        path: "/home/mpopov/.ssh"
        state: directory

    - name: Copy id_rsa.pub from control to managed machine
      copy:
        src: "~/.ssh/id_rsa.pub"
        dest: "/home/mpopov/.ssh/authorized_keys"

    - name: Create directory structure
      file: 
        path: "/home/mpopov/ops445/lab{{ item }}"
        state: directory
      loop:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
